drop table book;
CREATE TABLE book (
    id integer generated by default  as identity primary key ,
    self_link varchar(500),
    sale_info varchar(500),
    volume_info varchar(500)
);

drop table comment;
CREATE TABLE comment (
    id integer generated by default  as identity primary key ,
    text varchar(500),
    rating int,
    added_on varchar(30),
    user_id varchar(30),
    book_id varchar(30)
)
