drop table if exists book;

create table book
(
    id          integer generated by default as identity primary key,
    self_link   varchar(500),
    sale_info   varchar(500),
    volume_info varchar(500)
);


drop table if exists comment;
CREATE TABLE comment (
                         id integer generated by default  as identity primary key ,
                         text varchar(500),
                         rating int,
                         added_on varchar(30),
                         user_id varchar(30),
                         book_id varchar(30)
)